/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Operations {
  createdAt: Timestamp;
  id: string;
  operationDate: Timestamp;
  operationTypeId: string;
  productId: string;
  quantity: number;
  userId: string;
}

export interface OperationTypes {
  code: string;
  id: string;
}

export interface Products {
  article: string;
  createdAt: Timestamp;
  description: string | null;
  id: string;
  name: string;
  updatedAt: Timestamp;
}

export interface RefreshSessions {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  refreshTokenHash: string;
  userId: string;
}

export interface Roles {
  code: string;
  id: string;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  id: string;
  name: string;
  passwordHash: string;
  roleId: string;
  updatedAt: Timestamp;
}

export interface WarehouseSettings {
  capacity: number;
  id: string;
  updatedAt: Timestamp;
}

export interface DB {
  operations: Operations;
  operationTypes: OperationTypes;
  products: Products;
  refreshSessions: RefreshSessions;
  roles: Roles;
  users: Users;
  warehouseSettings: WarehouseSettings;
}
